### ISSUE TITLE
Placing Fabric on top of full Fabric block causes invisible texture

### ISSUE THREAD

**Issue by niraqw15** [malcolmriley/minecraft-textiles#31]
Placing fabric on top of a full block of fabric causes the top texture of the fabric block to become invisible. This only occurs when the fabric on top is facing the same way as the fabric on the bottom.

![2021-08-27_21 07 42](https://user-images.githubusercontent.com/22210045/131205824-92bea566-00e9-45d5-a380-53b5d906fdcd.png)

As a small side note, is it intentional that fabric of a different color can't be placed on top of a full block of fabric?

Minecraft: 1.16.5
Forge: 36.2.2
Mods: Wily Textiles: 0.1.2

**Comment by malcolmriley** [comment]
Hello,

Thank you for the report - Automation closed the issue before I got a chance to reply. Both issues have been resolved in pending version 0.1.3. Hopefully, CurseForge is processing it as you read this.

![resolved](https://user-images.githubusercontent.com/28375009/131209285-890f3008-0efb-4f96-ae6b-a32900e7b8d9.png)
