### ISSUE TITLE
Suggestion:  Plant Fiber drop rate tweaking

### ISSUE THREAD

**Issue by HopsandBarley** [malcolmriley/minecraft-textiles#47]
Just a few thoughts after a bit of testing.  

Plant fiber drop rates seem a little low.  takes a lot of grass chopping to get enough for 1 bale.  at least in my very limited testing.

If you start in a taiga, desert, badlands, etc, you aren't going to be able to get any plant fibers.  They don't seem to drop from ferns,(and I assume?) dead bushes?  

I'm going to change loot tables i think, for my pack, so it's not something that is critical.  For mainly vanilla packs, the drops might be fine.  but I've changed enough reicpes, that my brain is evaluating things differently.  lol

**Comment by malcolmriley** [comment]
Hello,

Thank you for the feedback. It is true that the drop rate of fibers from grass is low, but it is done so deliberately. It is possible, of course, that it is *too* low. I do have a few thoughts and justifications for why I did it this way:
- Grass foraging for fibers is intended to be a secondary source for creating fiber bales, the primary is intended to be flax farming
- There exists a crafting recipe from grasses or dead bushes into fibers directly, so obtaining shears means a guaranteed increase in fiber production from grasses if that's the desired route
- The fiber item can also be used by modpack makers as an intermediate in processing the flax stalks themselves in some way, or for processing other plants in their pack into fibers
- Dropping things from grass is a *very* well-trodden path in mods already, a lot of clutter results from breaking grass in most modpacks, so it would be best to keep grass drops minimal

I'm willing to be persuaded of course, but I'm fairly happy with where the fiber-from-grass drops are currently at. If there's some use case I haven't thought of or if there's some flaw to my thinking I'd be happy to hear it.

**Comment by HopsandBarley** [comment]
All valid points.  if the intent is to have the drops from grass be secondary, then it seems like it's at a pretty good spot.  

Side note, i looked through your 'Feature ideation' list, and am really excited about what you have planned, or at least what you are thinking.
