### ISSUE TITLE
1.18.2 How to re-craft retted fiber bales?

### ISSUE THREAD

**Issue by ZephyrWindSpirit** [malcolmriley/minecraft-textiles#57]
I'm building a ruined textile farm, and having small piles of retted fibers here and there as expired crop is an excellent idea for decoration. 

When I break them with my fist, it drops into twine. Do I need silk touch to get the bale itself or will there be a re-crafting recipe for twine into a bale?

**Comment by malcolmriley** [comment]
I assume this is for a survival build? The fully retted bale item is available in the Creative tab.

I didn't intend to add a re-crafting recipe for the retted bales. They don't currently drop with Silk Touch, but I don't think there's any harm in adding that.

In the meantime, one could cure the bales in their "resting place" and then remove the water with a bucket once they've reached maturity, or add a simple loot table datapack.
