### ISSUE TITLE
1.18.2 Wily textiles flax items are not compostable. 

### ISSUE THREAD

**Issue by ZephyrWindSpirit** [malcolmriley/minecraft-textiles#59]
None of the flax items are compostable. They should be. 
Please and thank you.

**Comment by malcolmriley** [comment]
Indeed, they should be. I'll put it on my to-do list for 0.4.0, thanks!

**Comment by malcolmriley** [comment]
I changed my mind and have built a minor release 0.3.3 for this feature and the other you suggested, and will be putting a small thank you in the change log crediting you with the suggestions.

Thanks again!

**Comment by ZephyrWindSpirit** [comment]
I am so excited! Will link pictures when my build is more complete
